name: client
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: mandui tech <email@example.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  tuple: ^1.0.2
  js: ^0.6.1+1

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
  # for scss support
  # a stackoverflow link https://stackoverflow.com/questions/50609938/use-scss-style-files-within-angulardart-5-and-dart-2
  sass_builder: ^2.1.2
